# Generated by Django 4.1.6 on 2023-02-02 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("buscaSaude", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bairro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(blank=True, max_length=255, null=True)),
                ("bairro", models.CharField(max_length=40)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Especialidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(blank=True, max_length=255, null=True)),
                ("especialidade", models.CharField(max_length=100)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(blank=True, max_length=255, null=True)),
                ("uf", models.CharField(max_length=20)),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="profile",
            name="favoritos",
            field=models.ManyToManyField(
                blank=True, related_name="favoritos", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(blank=True, max_length=255, null=True)),
                ("nome_do_local", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=150)),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=9)),
                ("funcionamento_horario_inicio", models.TimeField()),
                ("funcionamento_horario_fim", models.TimeField()),
                (
                    "funcionamento_dias",
                    models.IntegerField(
                        choices=[
                            (1, "Domingo"),
                            (2, "Segunda-Feira"),
                            (3, "Terça-Feira"),
                            (4, "Quarta-Feira"),
                            (5, "Quinta-Feira"),
                            (6, "Sexta-Feira"),
                            (7, "Sábado"),
                        ]
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "bairro",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bairro+",
                        to="buscaSaude.bairro",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Cidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(blank=True, max_length=255, null=True)),
                ("cidade", models.CharField(max_length=40)),
                (
                    "uf",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uf+",
                        to="buscaSaude.estado",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="bairro",
            name="cidade",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cidade+",
                to="buscaSaude.cidade",
            ),
        ),
        migrations.CreateModel(
            name="Avalicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(blank=True, max_length=255, null=True)),
                ("nota", models.DecimalField(decimal_places=2, max_digits=5)),
                ("comentarios", models.TextField(blank=True, null=True)),
                (
                    "user_avaliado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_avaliador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliou",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="profile",
            name="enderecos",
            field=models.ManyToManyField(to="buscaSaude.endereco"),
        ),
        migrations.AddField(
            model_name="profile",
            name="especialidades",
            field=models.ManyToManyField(to="buscaSaude.especialidade"),
        ),
    ]
