# Generated by Django 4.1.6 on 2023-02-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buscaSaude", "0002_bairro_especialidade_estado_profile_favoritos_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="avalicao",
            options={"verbose_name": "Avaliação", "verbose_name_plural": "Avaliações"},
        ),
    ]
