# Generated by Django 4.1.6 on 2023-02-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buscaSaude", "0003_alter_avalicao_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="endereco",
            options={"verbose_name": "Endereço", "verbose_name_plural": "Endereços"},
        ),
    ]
