# Generated by Django 4.1.6 on 2023-02-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buscaSaude", "0004_alter_endereco_options"),
    ]

    operations = [
        migrations.RemoveField(model_name="avalicao", name="token",),
        migrations.RemoveField(model_name="bairro", name="token",),
        migrations.RemoveField(model_name="cidade", name="token",),
        migrations.RemoveField(model_name="endereco", name="token",),
        migrations.RemoveField(model_name="especialidade", name="token",),
        migrations.RemoveField(model_name="estado", name="token",),
    ]
