# Generated by Django 4.1.6 on 2023-02-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buscaSaude", "0006_alter_endereco_latitude_alter_endereco_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endereco",
            name="funcionamento_dias",
            field=models.IntegerField(
                choices=[
                    (1, "2ª a 6ª"),
                    (2, "2ª a sábado"),
                    (3, "Somente com agendamento"),
                    (4, "Teleconsulta e Agendamento Presencial"),
                    (5, "Teleconsulta somente"),
                    (6, "Urgência e Emergência - 24hs"),
                ]
            ),
        ),
    ]
